name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [main] # Cambia a tu rama principal si no es main
  workflow_dispatch: # Permite ejecutar manualmente desde la pestaña Actions

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Usa la versión de Node que prefieras
          cache: 'npm' # Habilita caché para npm

      - name: Install dependencies
        run: npm install

      - name: Build Astro
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Carpeta donde Astro genera el sitio estático

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4